"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { contentApi } from "./api";
import { AdminPage } from "./admin-page";
import { ErrorState, LoadingState } from "./query-state";
import type { AdminMedia, AdminProject, Experience, ResumeDetail, ResumeRequest, Skill } from "./types";

type Selected = { id: string; custom: string };

export function AdminResumeEditor({ id }: { id: string | null }) {
  const resume = useQuery({ queryKey: ["admin", "resume", id], queryFn: () => contentApi.resume(id!), enabled: Boolean(id) });
  const experiences = useQuery({ queryKey: ["admin", "experiences"], queryFn: () => contentApi.list<Experience>("experiences") });
  const projects = useQuery({ queryKey: ["admin", "projects"], queryFn: contentApi.adminProjects });
  const skills = useQuery({ queryKey: ["admin", "skills"], queryFn: () => contentApi.list<Skill>("skills") });
  const media = useQuery({ queryKey: ["admin", "media"], queryFn: contentApi.media });
  if ((id && resume.isPending) || experiences.isPending || projects.isPending || skills.isPending || media.isPending) return <AdminPage title="이력서 편집"><LoadingState /></AdminPage>;
  if (resume.isError || experiences.isError || projects.isError || skills.isError || media.isError) return <AdminPage title="이력서 편집"><ErrorState /></AdminPage>;
  return <ResumeForm key={id ?? "new"} id={id} resume={resume.data ?? null} experiences={experiences.data ?? []} projects={projects.data?.content ?? []} skills={skills.data ?? []} media={media.data ?? []} />;
}

function ResumeForm({ id, resume, experiences, projects, skills, media }: { id: string | null; resume: ResumeDetail | null; experiences: Experience[]; projects: AdminProject[]; skills: Skill[]; media: AdminMedia[] }) {
  const router = useRouter(); const [selectedExperiences, setSelectedExperiences] = useState<Selected[]>(resume?.experiences.map((item) => ({ id: item.id, custom: item.description })) ?? []); const [selectedProjects, setSelectedProjects] = useState<Selected[]>(resume?.projects.map((item) => ({ id: item.id, custom: item.summary })) ?? []); const [selectedSkills, setSelectedSkills] = useState<string[]>(resume?.skills.map((item) => item.id) ?? []);
  const save = useMutation({ mutationFn: (body: ResumeRequest) => contentApi.saveResume(id, body), onSuccess: () => router.push("/admin/resumes") });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); save.mutate({ title: String(data.get("title")), companyName: String(data.get("companyName")), positionName: String(data.get("positionName")), jobPostingUrl: String(data.get("jobPostingUrl")) || null, deadline: String(data.get("deadline")) || null, customSummary: String(data.get("customSummary")), profileMediaId: String(data.get("profileMediaId")) || null, notes: String(data.get("notes")) || null, experiences: selectedExperiences.map((item, index) => ({ experienceId: item.id, displayOrder: index, customDescription: item.custom || null })), projects: selectedProjects.map((item, index) => ({ projectId: item.id, displayOrder: index, customSummary: item.custom || null })), skills: selectedSkills.map((skillId, index) => ({ skillId, displayOrder: index })) }); }
  return <AdminPage title={id ? "이력서 수정" : "이력서 추가"} description="선택 목록의 위·아래 버튼으로 PDF 표시 순서를 조정할 수 있습니다."><form className="rounded-2xl border border-line bg-surface p-6" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><Input label="이력서 제목" name="title" required value={resume?.title} /><Input label="회사명" name="companyName" required value={resume?.companyName} /><Input label="포지션명" name="positionName" required value={resume?.positionName} /><Input label="채용공고 URL(HTTPS)" name="jobPostingUrl" type="url" value={resume?.jobPostingUrl} /><Input label="마감일" name="deadline" type="date" value={resume?.deadline} /><label><span className="mb-2 block text-sm font-semibold">프로필 이미지(선택)</span><select className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" defaultValue={resume?.profileMediaId ?? ""} name="profileMediaId"><option value="">사용하지 않음</option>{media.filter((item) => item.mimeType.startsWith("image/")).map((item) => <option key={item.id} value={item.id}>{item.originalName}</option>)}</select></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">맞춤 요약</span><textarea className="min-h-32 w-full rounded-lg border border-line p-3 text-sm" defaultValue={resume?.customSummary ?? ""} maxLength={10000} name="customSummary" required /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">비공개 메모</span><textarea className="min-h-24 w-full rounded-lg border border-line p-3 text-sm" defaultValue={resume?.notes ?? ""} maxLength={20000} name="notes" /></label></div>
    <Picker title="경력 선택" items={experiences.map((item) => ({ id: item.id, label: `${item.organization} · ${item.title}`, fallback: item.description }))} selected={selectedExperiences} setSelected={setSelectedExperiences} withCustom />
    <Picker title="프로젝트 선택" items={projects.map((item) => ({ id: item.id, label: item.title, fallback: item.summary }))} selected={selectedProjects} setSelected={setSelectedProjects} withCustom />
    <Picker title="기술 강조 순서" items={skills.map((item) => ({ id: item.id, label: `${item.name} · ${item.category}`, fallback: "" }))} selected={selectedSkills.map((id) => ({ id, custom: "" }))} setSelected={(items) => setSelectedSkills(items.map((item) => item.id))} />
    {save.isError && <p className="mt-5 text-sm text-red-700" role="alert">저장하지 못했습니다. 필수값과 URL, 선택 항목을 확인해 주세요.</p>}<div className="mt-7 flex gap-3"><button className="rounded-lg bg-accent px-5 py-3 text-sm font-semibold text-white disabled:opacity-50" disabled={save.isPending} type="submit">{save.isPending ? "저장 중…" : "이력서 저장"}</button><button className="rounded-lg border border-line px-5 py-3 text-sm font-semibold" onClick={() => router.push("/admin/resumes")} type="button">취소</button></div></form></AdminPage>;
}

function Picker({ title, items, selected, setSelected, withCustom = false }: { title: string; items: Array<{ id: string; label: string; fallback: string }>; selected: Selected[]; setSelected: (items: Selected[]) => void; withCustom?: boolean }) { function toggle(item: { id: string; fallback: string }, checked: boolean) { setSelected(checked ? [...selected, { id: item.id, custom: item.fallback }] : selected.filter((value) => value.id !== item.id)); } function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= selected.length) return; const copy = [...selected]; [copy[index], copy[target]] = [copy[target], copy[index]]; setSelected(copy); } return <fieldset className="mt-8"><legend className="text-lg font-semibold">{title}</legend><div className="mt-3 flex flex-wrap gap-2">{items.map((item) => <label className="flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-sm" key={item.id}><input checked={selected.some((value) => value.id === item.id)} onChange={(event) => toggle(item, event.target.checked)} type="checkbox" />{item.label}</label>)}</div><ol className="mt-4 grid gap-3">{selected.map((value, index) => { const source = items.find((item) => item.id === value.id); return <li className="rounded-xl border border-line p-4" key={value.id}><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold">{index + 1}. {source?.label}</span><div className="flex gap-2"><button aria-label={`${source?.label} 위로`} className="rounded border border-line px-2" disabled={index === 0} onClick={() => move(index, -1)} type="button">↑</button><button aria-label={`${source?.label} 아래로`} className="rounded border border-line px-2" disabled={index === selected.length - 1} onClick={() => move(index, 1)} type="button">↓</button></div></div>{withCustom && <textarea aria-label={`${source?.label} 맞춤 설명`} className="mt-3 min-h-20 w-full rounded-lg border border-line p-2 text-sm" onChange={(event) => setSelected(selected.map((item, i) => i === index ? { ...item, custom: event.target.value } : item))} value={value.custom} />}</li>; })}</ol></fieldset>; }
function Input({ label, value, ...props }: { label: string; value?: string | null } & Omit<React.InputHTMLAttributes<HTMLInputElement>, "value" | "defaultValue">) { return <label><span className="mb-2 block text-sm font-semibold">{label}</span><input {...props} className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" defaultValue={value ?? ""} /></label>; }
