/* eslint-disable @next/next/no-img-element */
"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ApiError } from "@/features/auth/api";
import { contentApi, mediaUrl } from "./api";
import { AdminPage } from "./admin-page";
import { ErrorState, LoadingState } from "./query-state";
import type { AdminMedia, AdminProjectMedia } from "./types";

const roles = ["COVER", "CONTENT", "ARCHITECTURE", "DASHBOARD", "RESULT"] as const;

export function AdminMediaManager() {
  const client = useQueryClient(); const [selectedProject, setSelectedProject] = useState(""); const [clientError, setClientError] = useState(""); const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const media = useQuery({ queryKey: ["admin", "media"], queryFn: contentApi.media });
  const projects = useQuery({ queryKey: ["admin", "projects"], queryFn: contentApi.adminProjects });
  const attached = useQuery({ queryKey: ["admin", "project-media", selectedProject], queryFn: () => contentApi.projectMedia(selectedProject), enabled: Boolean(selectedProject) });
  const upload = useMutation({ mutationFn: contentApi.uploadMedia, onSuccess: () => client.invalidateQueries({ queryKey: ["admin", "media"] }) });
  const attach = useMutation({ mutationFn: ({ mediaId, mediaRole, displayOrder }: { mediaId: string; mediaRole: string; displayOrder: number }) => contentApi.attachMedia(selectedProject, { mediaId, mediaRole, displayOrder }), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin", "media"] }); client.invalidateQueries({ queryKey: ["admin", "project-media", selectedProject] }); } });
  const reorder = useMutation({ mutationFn: (items: AdminProjectMedia[]) => contentApi.reorderMedia(selectedProject, items.map((item, index) => ({ projectMediaId: item.id, displayOrder: index }))), onSuccess: () => client.invalidateQueries({ queryKey: ["admin", "project-media", selectedProject] }) });
  const detach = useMutation({ mutationFn: (id: string) => contentApi.detachMedia(selectedProject, id), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin", "media"] }); client.invalidateQueries({ queryKey: ["admin", "project-media", selectedProject] }); } });

  function submitUpload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setClientError(""); const form = event.currentTarget; if (!selectedFile?.size) return setClientError("이미지 파일을 선택해 주세요."); if (selectedFile.size > 5 * 1024 * 1024) return setClientError("파일은 5MB 이하여야 합니다."); if (!["image/png", "image/jpeg"].includes(selectedFile.type)) return setClientError("PNG 또는 JPEG 파일만 업로드할 수 있습니다."); const data = new FormData(form); data.set("file", selectedFile); upload.mutate(data, { onSuccess: () => { form.reset(); setSelectedFile(null); } }); }
  function submitAttach(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); attach.mutate({ mediaId: String(data.get("mediaId")), mediaRole: String(data.get("mediaRole")), displayOrder: Number(data.get("displayOrder")) }); }
  function move(index: number, direction: -1 | 1) { if (!attached.data) return; const target = index + direction; if (target < 0 || target >= attached.data.length) return; const items = [...attached.data]; [items[index], items[target]] = [items[target], items[index]]; reorder.mutate(items); }

  return <AdminPage title="미디어" description="PNG·JPEG, 최대 5MB. 업로드한 뒤 프로젝트 역할과 표시 순서를 지정합니다.">
    <form className="rounded-2xl border border-line bg-surface p-6" encType="multipart/form-data" onSubmit={submitUpload}><h2 className="text-lg font-semibold">이미지 업로드</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">파일</span><input accept=".png,.jpg,.jpeg,image/png,image/jpeg" className="block w-full text-sm" name="file" onChange={(event) => setSelectedFile(event.target.files?.[0] ?? null)} required type="file" /></label><label><span className="mb-2 block text-sm font-semibold">대체 텍스트</span><input className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" maxLength={300} name="altText" required /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">캡션(선택)</span><input className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" maxLength={1000} name="caption" /></label></div>{(clientError || upload.error) && <p className="mt-4 text-sm text-red-700" role="alert">{clientError || errorMessage(upload.error)}</p>}<button className="mt-5 rounded-lg bg-accent px-5 py-3 text-sm font-semibold text-white disabled:opacity-50" disabled={upload.isPending} type="submit">{upload.isPending ? "업로드 중…" : "업로드"}</button></form>
    <section className="mt-8" aria-labelledby="library-title"><h2 className="text-xl font-semibold" id="library-title">파일 보관함</h2>{media.isPending && <div className="mt-4"><LoadingState /></div>}{media.isError && <div className="mt-4"><ErrorState retry={() => media.refetch()} /></div>}<div className="mt-4 grid gap-4 md:grid-cols-2">{media.data?.map((item) => <MediaCard item={item} key={item.id} />)}</div>{media.data?.length === 0 && <p className="mt-4 rounded-xl border border-dashed border-line p-6 text-sm text-muted">업로드된 파일이 없습니다.</p>}</section>
    <section className="mt-10 rounded-2xl border border-line bg-surface p-6" aria-labelledby="assignment-title"><h2 className="text-xl font-semibold" id="assignment-title">프로젝트 배치</h2><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">프로젝트</span><select className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" onChange={(e) => setSelectedProject(e.target.value)} value={selectedProject}><option value="">선택하세요</option>{projects.data?.content.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label>{selectedProject && <><form className="mt-5 grid gap-4 sm:grid-cols-4" onSubmit={submitAttach}><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">미디어</span><select className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" name="mediaId" required><option value="">선택하세요</option>{media.data?.filter((item) => item.mimeType.startsWith("image/")).map((item) => <option key={item.id} value={item.id}>{item.originalName}</option>)}</select></label><label><span className="mb-2 block text-sm font-semibold">역할</span><select className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" name="mediaRole">{roles.map((role) => <option key={role}>{role}</option>)}</select></label><label><span className="mb-2 block text-sm font-semibold">순서</span><input className="min-h-11 w-full rounded-lg border border-line px-3 text-sm" defaultValue={attached.data?.length ?? 0} min={0} name="displayOrder" type="number" /></label><button className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white sm:col-span-4" disabled={attach.isPending} type="submit">프로젝트에 연결</button></form>{attach.error && <p className="mt-3 text-sm text-red-700" role="alert">{errorMessage(attach.error)}</p>}<ul className="mt-6 divide-y divide-line">{attached.data?.map((item, index) => <li className="flex flex-wrap items-center justify-between gap-3 py-3" key={item.id}><span className="text-sm"><b>{item.mediaRole}</b> · {item.originalName}</span><div className="flex gap-2"><button aria-label={`${item.originalName} 위로`} className="rounded border border-line px-2 py-1" disabled={index === 0 || reorder.isPending} onClick={() => move(index, -1)} type="button">↑</button><button aria-label={`${item.originalName} 아래로`} className="rounded border border-line px-2 py-1" disabled={index === (attached.data?.length ?? 0) - 1 || reorder.isPending} onClick={() => move(index, 1)} type="button">↓</button><button className="rounded border border-red-200 px-2 py-1 text-sm text-red-700" onClick={() => detach.mutate(item.id)} type="button">연결 해제</button></div></li>)}</ul></>}</section>
  </AdminPage>;
}

function MediaCard({ item }: { item: AdminMedia }) { const client = useQueryClient(); const update = useMutation({ mutationFn: (body: { altText: string; caption: string | null }) => contentApi.updateMedia(item.id, body), onSuccess: () => client.invalidateQueries({ queryKey: ["admin", "media"] }) }); const remove = useMutation({ mutationFn: () => contentApi.removeMedia(item.id), onSuccess: () => client.invalidateQueries({ queryKey: ["admin", "media"] }) }); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); update.mutate({ altText: String(data.get("altText")), caption: String(data.get("caption")) || null }); } const isImage = item.mimeType.startsWith("image/") && item.width && item.height; return <article className="rounded-2xl border border-line bg-surface p-5">{isImage ? <img alt={item.altText} className="aspect-video w-full rounded-lg bg-canvas object-contain" height={item.height!} src={mediaUrl(item.url)} width={item.width!} /> : <div className="flex aspect-video items-center justify-center rounded-lg bg-canvas text-sm font-semibold text-muted">PDF 문서</div>}<p className="mt-3 truncate text-sm font-semibold" title={item.originalName}>{item.originalName}</p><p className="mt-1 text-xs text-muted">{isImage ? `${item.width}×${item.height} · ` : ""}{(item.fileSize / 1024).toFixed(1)}KB · 사용 {item.usageCount}곳</p><form className="mt-4 grid gap-3" onSubmit={submit}><input aria-label={`${item.originalName} 대체 텍스트`} className="min-h-10 rounded-lg border border-line px-3 text-sm" defaultValue={item.altText} maxLength={300} name="altText" required /><input aria-label={`${item.originalName} 캡션`} className="min-h-10 rounded-lg border border-line px-3 text-sm" defaultValue={item.caption ?? ""} maxLength={1000} name="caption" /><div className="flex gap-2"><button className="rounded-lg border border-line px-3 py-2 text-sm font-semibold" disabled={update.isPending} type="submit">메타데이터 저장</button><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 disabled:opacity-50" disabled={item.usageCount > 0 || remove.isPending} onClick={() => { if (window.confirm("미사용 파일을 삭제하시겠습니까?")) remove.mutate(); }} type="button">삭제</button></div></form>{(update.error || remove.error) && <p className="mt-3 text-sm text-red-700" role="alert">{errorMessage(update.error ?? remove.error)}</p>}</article>; }
function errorMessage(error: Error | null) { return error instanceof ApiError ? error.message : "요청을 처리하지 못했습니다."; }
